# Generated by Django 4.2.27 on 2025-12-22 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('RAZORPAY', 'Razorpay')], default='RAZORPAY', max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('CAPTURED', 'Captured'), ('FAILED', 'Failed')], default='CREATED', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider_order_id', models.CharField(blank=True, max_length=120)),
                ('provider_payment_id', models.CharField(blank=True, max_length=120)),
                ('provider_signature', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
        ),
    ]
