# Generated by Django 4.2.27 on 2025-12-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                (
                    'method_type',
                    models.CharField(
                        choices=[('UPI', 'UPI'), ('BANK', 'Bank Transfer'), ('QR', 'QR Code'), ('OTHER', 'Other')],
                        default='UPI',
                        max_length=20,
                    ),
                ),
                ('upi_id', models.CharField(blank=True, max_length=120)),
                ('account_name', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='payment_methods/')),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='manual_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='manual_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(
                choices=[('RAZORPAY', 'Razorpay'), ('MANUAL', 'Manual')],
                default='RAZORPAY',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(
                choices=[
                    ('CREATED', 'Created'),
                    ('SUBMITTED', 'Submitted'),
                    ('CAPTURED', 'Captured'),
                    ('VERIFIED', 'Verified'),
                    ('FAILED', 'Failed'),
                ],
                default='CREATED',
                max_length=20,
            ),
        ),
    ]
