# Generated by Django 4.2.27 on 2025-12-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentmethod_and_manual_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(
                choices=[('MANUAL', 'Manual')],
                default='MANUAL',
                max_length=20,
            ),
        ),
    ]
