# Generated by Django 4.2.27 on 2025-12-29 05:30

from django.db import migrations


UPI_ID = '7851985710-4@ybl'


def seed_default_payment_methods(apps, schema_editor):
    PaymentMethod = apps.get_model('payments', 'PaymentMethod')

    desired = [
        {
            'method_type': 'QR',
            'name': 'Scan & Pay (QR)',
            'defaults': {
                'upi_id': UPI_ID,
                'account_name': 'SR TRADERS',
                'instructions': 'Scan the QR and pay using any UPI app. Then enter your UTR/Transaction ID.',
                'is_active': True,
                'sort_order': 0,
            },
        },
        {
            'method_type': 'UPI',
            'name': 'UPI',
            'defaults': {
                'upi_id': UPI_ID,
                'account_name': 'SR TRADERS',
                'instructions': 'Pay to this UPI ID and enter your UTR/Transaction ID.',
                'is_active': True,
                'sort_order': 1,
            },
        },
    ]

    keep_ids = []
    for item in desired:
        obj, _ = PaymentMethod.objects.update_or_create(
            method_type=item['method_type'],
            name=item['name'],
            defaults=item['defaults'],
        )
        keep_ids.append(obj.id)

    PaymentMethod.objects.exclude(id__in=keep_ids).update(is_active=False)


def unseed_default_payment_methods(apps, schema_editor):
    PaymentMethod = apps.get_model('payments', 'PaymentMethod')

    PaymentMethod.objects.filter(method_type='QR', name='Scan & Pay (QR)', upi_id=UPI_ID).update(is_active=False)
    PaymentMethod.objects.filter(method_type='UPI', name='UPI', upi_id=UPI_ID).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_provider'),
    ]

    operations = [
        migrations.RunPython(seed_default_payment_methods, unseed_default_payment_methods),
    ]
