# Generated by Django 4.2.27 on 2025-12-23 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentmethod_and_manual_fields'),
        ('orders', '0002_orderitem_size_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manual_payment_method',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='orders',
                to='payments.paymentmethod',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('COD', 'Cash on Delivery'),
                    ('RAZORPAY', 'Razorpay'),
                    ('MANUAL', 'UPI/Bank (Manual)'),
                ],
                default='COD',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING_PAYMENT', 'Pending Payment'),
                    ('PAYMENT_SUBMITTED', 'Payment Submitted'),
                    ('PLACED', 'Placed'),
                    ('PAID', 'Paid'),
                    ('SHIPPED', 'Shipped'),
                    ('DELIVERED', 'Delivered'),
                    ('CANCELLED', 'Cancelled'),
                ],
                default='PLACED',
                max_length=20,
            ),
        ),
    ]
