# Generated by Django 4.2.27 on 2025-12-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_cod_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(
                choices=[('MANUAL', 'UPI/Bank (Manual)')],
                default='MANUAL',
                max_length=20,
            ),
        ),
    ]
